/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TestMain;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Deathwarror
 */
public class MainGUI extends javax.swing.JFrame {

    DefaultListModel listModel;
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();

        listModel = new DefaultListModel();
        FileListBox.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        FileListBox = new javax.swing.JList();
        AddButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CodeBox = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ErrorBox = new javax.swing.JTextArea();
        FileListTitle = new javax.swing.JLabel();
        CodeListTitle = new javax.swing.JLabel();
        ErrorMsgTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Linting Tool");

        FileListBox.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        FileListBox.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                FileListBoxValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(FileListBox);

        AddButton.setText("Load File");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        RemoveButton.setText("Remove File");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        CodeBox.setColumns(20);
        CodeBox.setRows(5);
        jScrollPane2.setViewportView(CodeBox);

        ErrorBox.setColumns(20);
        ErrorBox.setRows(5);
        jScrollPane3.setViewportView(ErrorBox);

        FileListTitle.setText("Files Opened");

        CodeListTitle.setText("File data");

        ErrorMsgTitle.setText("Error Messages");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FileListTitle)
                            .addComponent(ErrorMsgTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RemoveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CodeListTitle)
                                .addContainerGap())
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodeListTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddButton)
                            .addComponent(RemoveButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ErrorMsgTitle))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        SimpleFileStore newFile = new SimpleFileStore();
        FileRead FR = new FileRead();
        Parser parser;
        ErrorSearcher ES = new ErrorSearcher();
        FR.newFile();
        if(!FR.getFileName().equals(""))
        {
            newFile.setCode(FR.getCode());
            newFile.setName(FR.getFileName());
            parser = new Parser(newFile.getCode());
            newFile.setErrorList(ES.Start(parser));
            listModel.addElement(newFile);
            FileListBox.setSelectedIndex(listModel.size()-1);
            FileListBox.ensureIndexIsVisible(listModel.size()-1);
            ErrorBox.setEditable(false);
            ErrorBox.setWrapStyleWord(true);
            CodeBox.setEditable(false);
            CodeBox.setWrapStyleWord(true);
        }
        else
        {
            JFrame frame = new JFrame("File Read Error");
            JOptionPane.showMessageDialog(frame, "Error the File Failed to Read");
        }

    }//GEN-LAST:event_AddButtonActionPerformed

    private void FileListBoxValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_FileListBoxValueChanged
        // TODO add your handling code here:
        if(evt.getValueIsAdjusting()==false)
        {
            int index = FileListBox.getSelectedIndex();
            SimpleFileStore WorkingStore;
            ArrayList<String> Code;
            ArrayList<Error> Errors;
            String FileCode = "";
            String ErrorList = "";
            if(index == -1)
            {
                RemoveButton.setEnabled(false);
                CodeBox.setText(" ");
                ErrorBox.setText(" ");
            }
            else
            {
                WorkingStore = (SimpleFileStore) listModel.get(index);
                Code = WorkingStore.getCode();
                Errors = WorkingStore.getErrorList();
                RemoveButton.setEnabled(true);
                for(int i = 0; i<Code.size();i++)
                {
                    FileCode = FileCode+(i+1)+":\t"+Code.get(i)+"\n";
                }
                CodeBox.setText(FileCode);
                for(int i = 0; i<Errors.size();i++)
                {
                    Error e = Errors.get(i);
                    ErrorList = ErrorList+e.getErrorNum()+":  "+e.getErrorMsg()+"\n\n";
                }
                if(ErrorList.equals(""))
                {
                    ErrorBox.setText("No Errors Detected");
                }
                else
                {
                    ErrorBox.setText(ErrorList);
                }
            }
        }
    }//GEN-LAST:event_FileListBoxValueChanged

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        int index = FileListBox.getSelectedIndex();
        if(index != -1)
        {
             String FileName = ((SimpleFileStore) listModel.get(index)).getName();
             listModel.remove(index);
        }

        int size = listModel.getSize();
        if(size == 0)
        {
            RemoveButton.setEnabled(false);
        }
        else
        {
            if(index == listModel.getSize())
            {
                index--;
            }
            FileListBox.setSelectedIndex(index);
            FileListBox.ensureIndexIsVisible(index);
        }

    }//GEN-LAST:event_RemoveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextArea CodeBox;
    private javax.swing.JLabel CodeListTitle;
    private javax.swing.JTextArea ErrorBox;
    private javax.swing.JLabel ErrorMsgTitle;
    private javax.swing.JList FileListBox;
    private javax.swing.JLabel FileListTitle;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
